### ISSUE TITLE
http to https redirect

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/dotc-jira_dc#5]
The system will have the ability to automatically redirect a user attempting to access the system via http to https.

Originally reported by @murphyj21 via GitLab/Jira. Moving to cardinal project...

**Comment by ferricoxide** [comment]
Two choices for this:
* Nuke the port-80 redirection from the ELB/ALB (and ensure documentation indicates as much)
* Add an Nginx listener at port 80 that performs a redirect.

The former is, quite obviously, dead-easy to do. The latter is probably the "friendlier" option, but requires adding another service to the back-end instance to listen for the ELB/ALB's proxied port-80 request (and send a 301 pointing to the proper URL).

**Comment by murphyj21** [comment]
Either will work on the other networks so I'll defer to your expertise on the direction to go.

**Comment by ferricoxide** [comment]
GitLab already listens at 80 by way of an embedded-Nginx... I can probably change the port the embedded Nginx listens on and then maybe try adding a secondary, "redirect only" Nginx. However, that seems kinda of heavy-handed. Path of least resistance is get rid of the ELB/ALB port 80 listener.

**Comment by ferricoxide** [comment]
GitLab already listens at 80 by way of an embedded-Nginx... I can probably change the port the embedded Nginx listens on and then maybe try adding a secondary, "redirect only" Nginx. However, that seems kinda of heavy-handed. Path of least resistance is get rid of the ELB/ALB port 80 listener.

**Comment by ferricoxide** [comment]
Actually, it occurs to me: since the `external_url` value is set to `https`, it _should_ already be redirecting?

**Comment by ferricoxide** [comment]
We implemented in dev by only having 443 in the ELB. Closing.
